In [1]:
import numpy as np

In [10]:
arr = np.zeros(10)

In [11]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
arr = np.ones(10)

In [13]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
arr = np.ones(10)*5

In [18]:
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [21]:
arr = np.arange(10,51)

In [22]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [31]:
arr = np.arange(10,51,2)

In [32]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [33]:
arr = np.arange(0,9).reshape(3,3)

In [34]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
np.random.rand(1)

array([0.10866713])

In [43]:
np.random.rand(25)

array([0.28498148, 0.8095634 , 0.10450817, 0.07522418, 0.8557667 ,
       0.81025882, 0.19092444, 0.28785107, 0.35299816, 0.10456385,
       0.34757188, 0.99470401, 0.8349744 , 0.76745559, 0.16744979,
       0.20692465, 0.02956997, 0.80148478, 0.65965161, 0.12065006,
       0.64468145, 0.60737672, 0.56955671, 0.28291311, 0.73442895])

In [52]:
arr = np.arange(1,101)/100

In [53]:
arr

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [54]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [55]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [59]:
arr = np.array([[12,13,14,15],[17,18,19,20],[22,23,24,25]])

In [60]:
arr

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [61]:
mat = np.arange(1,26).reshape(5,5)

In [62]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [63]:
mat.sum()

325

In [65]:
mat.std()

7.211102550927978

In [71]:
(mat.sum(axis=0)).sum()

325