In [2]:
pip install numpy


In [1]:
import numpy as np


In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
myarr = np.array(mylist)

In [6]:
type(myarr)

numpy.ndarray

In [14]:
mymatrix = [[1,2,3],[4,5,6],[7,8,9]]


In [15]:
np.array(mymatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [18]:
np.arange(0,200,30)

array([  0,  30,  60,  90, 120, 150, 180])

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones((2,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [23]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [24]:
len(np.linspace(0,5,21))

21

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.random.rand(1)

array([0.2980616])

In [30]:
np.random.rand(3,3)

array([[0.78152552, 0.67680847, 0.50532331],
       [0.25032514, 0.07523951, 0.21739368],
       [0.86064112, 0.8474379 , 0.51603521]])

In [31]:
np.random.randn(10)

array([-1.43193542, -0.38852203,  1.50713653, -1.11935296, -0.66228366,
        1.53010599, -1.6704366 ,  0.03639028,  0.11500572,  0.08996886])

In [32]:
np.random.randn(2,3)

array([[ 0.71428961, -0.36968797,  0.28687695],
       [-0.61149964, -0.33406688,  0.63401056]])

In [33]:
np.random.randint(10)

5

In [34]:
np.random.randint(0,101,5)

array([30, 82, 19, 85, 31])

In [35]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [36]:
np.random.rand(4)

array([0.68527698, 0.83389686, 0.30696622, 0.89361308])

In [37]:
arr = np.arange(0,25)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [41]:
ranrr = np.random.randint(0,101,10)

In [42]:
ranrr

array([60, 92, 64,  5, 12, 93, 40, 49, 83,  8])

In [45]:
ranrr.max()

93

In [46]:
ranrr.min()

5

In [47]:
ranrr.argmax()

5

In [48]:
ranrr.argmin()

3

In [49]:
ranrr.dtype

dtype('int32')

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
arr.shape

(25,)

In [52]:
arr = arr.reshape(5,5)

In [53]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
arr.shape

(5, 5)

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]

8

In [7]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [8]:
arr[:4]

array([0, 1, 2, 3])

In [9]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[0:3] = 100

In [11]:
arr

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [12]:
arr = np.arange(0,11)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
slice_of_arr = arr[0:5]

In [15]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
slice_of_arr[:] = 99

In [18]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [19]:
arr_copy = arr.copy()

In [20]:
arr_copy[:] = 100

In [21]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [22]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [24]:
arr_2d = np.array([[5,10,15],[20,25,40],[12,45,23]])

In [25]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 40],
       [12, 45, 23]])

In [26]:
arr_2d.shape

(3, 3)

In [27]:
arr_2d[0]

array([ 5, 10, 15])

In [29]:
arr_2d[1,2]

40

In [30]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 40]])

In [31]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 40]])

In [32]:
arr = np.arange(0,11)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
bool_arr = arr>4

In [37]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [38]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [4]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])



In [6]:
dice_rolls

array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6,
       3, 6, 2, 3, 5, 6, 5])

In [7]:
dice_rolls>2

array([ True, False,  True, False,  True, False, False,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True])

In [8]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])



In [10]:
dice_rolls

array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6,
       3, 6, 2, 3, 5, 6, 5])

In [11]:
total_rolls_over_two = len(dice_rolls[dice_rolls>2])


In [13]:
total_rolls_over_two

19

#NUMPY OPERATIONS

In [14]:
arr = np.arange(0,11)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
arr + 65

array([65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75])

In [18]:
arr - 12

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2])

In [19]:
arr * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [20]:
arr / 1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
arr / 0

C:\Users\aarav\AppData\Local\Temp\ipykernel_13220\3942562399.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr / 0
C:\Users\aarav\AppData\Local\Temp\ipykernel_13220\3942562399.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / 0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [22]:
arr + arr


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [23]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [25]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [26]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566,
        0.64836083])

In [27]:
arr.sum()

55

In [28]:
arr.mean()

5.0

In [30]:
arr.var()

10.0

In [31]:
arr.std()

3.1622776601683795

In [34]:
arr2d = np.arange(0,25).reshape(5,5)

In [35]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [37]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])